version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  assignees:
  - fabianfreyer
  ignore:
  - dependency-name: number_prefix
    versions:
    - 0.4.0
  - dependency-name: nix
    versions:
    - 0.19.0
    - 0.20.0
  - dependency-name: users
    versions:
    - 0.11.0
